version: '3.4'

services:
  myrecipe.api:
    image: ${DOCKER_REGISTRY-}myrecipeapi
    build:
      context: .
      dockerfile: MyRecipe.Api/Dockerfile
    depends_on:
      - myrecipe.db
  myrecipe.db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
        SA_PASSWORD: "sa@22702406"
        ACCEPT_EULA: "Y"